name: Test

on:
  pull_request:
    branches: [main]

jobs:
  go:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Run tests
        run: make build-and-test
